/* Generated by           cobc 3.1.2.0 */
/* Generated from         hellocobol.cob */
/* Generated at           Aug 04 2025 19:08:23 */
/* GnuCOBOL build date    Jul 15 2023 12:00:00 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -x -g -o hellocobol hellocobol.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};


/* Constants */
static const cob_field c_1	= {13, (cob_u8_ptr)"Hello, world!", &a_1};


/* Strings */
static const char st_1[]	= "DISPLAY";
static const char st_2[]	= "STOP RUN";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"hellocobol.cob"};
