/* Generated by           cobc 3.1.2.0 */
/* Generated from         hellocobol_if.cob */
/* Generated at           Aug 04 2025 19:27:10 */
/* GnuCOBOL build date    Jul 15 2023 12:00:00 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -x -g -o hellocobol_if hellocobol_if.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x10,   9,   0, 0x0001, NULL};
static const cob_field_attr a_3 =	{0x21,   0,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {16, (cob_u8_ptr)"ENTER number 1: ", &a_1};
static const cob_field c_2	= {16, (cob_u8_ptr)"ENTER number 2: ", &a_1};
static const cob_field c_3	= {17, (cob_u8_ptr)"ENTER some data: ", &a_1};
static const cob_field c_4	= {31, (cob_u8_ptr)"Number1 is greater than Number2", &a_1};
static const cob_field c_5	= {22, (cob_u8_ptr)"Number1 equals Number2", &a_1};
static const cob_field c_6	= {28, (cob_u8_ptr)"Number1 is less than Number2", &a_1};
static const cob_field c_7	= {19, (cob_u8_ptr)"Number1 is positive", &a_1};
static const cob_field c_8	= {19, (cob_u8_ptr)"Number1 is negative", &a_1};
static const cob_field c_9	= {12, (cob_u8_ptr)"Numeric data", &a_1};
static const cob_field c_10	= {15, (cob_u8_ptr)"Alphabetic data", &a_1};
static const cob_field c_11	= {27, (cob_u8_ptr)"Number1 is greater than 100", &a_1};
static const cob_field c_12	= {24, (cob_u8_ptr)"Number1 is less than 100", &a_1};
static const cob_field c_13	= {27, (cob_u8_ptr)"Number2 is greater than 100", &a_1};
static const cob_field c_14	= {24, (cob_u8_ptr)"Number2 is less than 100", &a_1};
static const cob_field c_15	= {36, (cob_u8_ptr)"Both of numbers are greater than 100", &a_1};


/* Strings */
static const char st_1[]	= "DISPLAY";
static const char st_2[]	= "ACCEPT";
static const char st_3[]	= "IF";
static const char st_4[]	= "STOP RUN";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"hellocobol_if.cob"};
