/* Generated by           cobc 3.1.2.0 */
/* Generated from         hellocobol_if.cob */
/* Generated at           Aug 04 2025 19:27:10 */
/* GnuCOBOL build date    Jul 15 2023 12:00:00 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -x -g -o hellocobol_if hellocobol_if.cob */

/* Program local variables for '01_IF' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_8[9] __attribute__((aligned));	/* var-num1 */
static cob_u8_t	b_10[9] __attribute__((aligned));	/* var-num2 */
static cob_u8_t	b_12[9] __attribute__((aligned));	/* var-data */

/* End of local data storage */


/* Fields (local) */
static cob_field f_8	= {9, b_8, &a_2};	/* var-num1 */
static cob_field f_10	= {9, b_10, &a_2};	/* var-num2 */
static cob_field f_12	= {9, b_12, &a_3};	/* var-data */

/* End of fields */

