/* Generated by           cobc 3.1.2.0 */
/* Generated from         hellocobol_variables.cob */
/* Generated at           Aug 04 2025 19:18:38 */
/* GnuCOBOL build date    Jul 15 2023 12:00:00 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -x -g -o hellocobol_variables hellocobol_variables.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Picture strings */

static const cob_pic_symbol p_1[] = {
	{'Z', 10},
	{'\0', 1}
};
static const cob_pic_symbol p_2[] = {
	{'+', 1},
	{'Z', 7},
	{'.', 1},
	{'Z', 2},
	{'\0', 1}
};
static const cob_pic_symbol p_3[] = {
	{'$', 1},
	{'Z', 7},
	{'.', 1},
	{'Z', 2},
	{'\0', 1}
};


/* Attributes */

static const cob_field_attr a_1 =	{0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x10,   4,   0, 0x1000, NULL};
static const cob_field_attr a_4 =	{0x24,  10,   0, 0x0000, p_1};
static const cob_field_attr a_5 =	{0x10,   1,   0, 0x1000, NULL};
static const cob_field_attr a_6 =	{0x10,   5,   2, 0x0007, NULL};
static const cob_field_attr a_7 =	{0x24,   9,   2, 0x0001, p_2};
static const cob_field_attr a_8 =	{0x10,   5,   2, 0x1000, NULL};
static const cob_field_attr a_9 =	{0x24,   9,   2, 0x0000, p_3};


/* Constants */
static const cob_field c_1	= {4, (cob_u8_ptr)"3721", &a_3};
static const cob_field c_2	= {1, (cob_u8_ptr)"0", &a_5};
static const cob_field c_3	= {6, (cob_u8_ptr)"-31721", &a_6};
static const cob_field c_4	= {5, (cob_u8_ptr)"31721", &a_8};


/* Strings */
static const char st_1[]	= "DISPLAY";
static const char st_2[]	= "MOVE";
static const char st_3[]	= "STOP RUN";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"hellocobol_variables.cob"};
