/* Generated by           cobc 3.1.2.0 */
/* Generated from         hellocobol_variables.cob */
/* Generated at           Aug 04 2025 19:18:38 */
/* GnuCOBOL build date    Jul 15 2023 12:00:00 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -x -g -o hellocobol_variables hellocobol_variables.cob */

/* Program local variables for '02_VARIABLES' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_8[35] __attribute__((aligned));	/* struct-headers */
static cob_u8_t	b_16[80] __attribute__((aligned));	/* var-line */
static cob_u8_t	b_17[37] __attribute__((aligned));	/* struct-row */

/* End of local data storage */


/* Fields (local) */
static cob_field f_8	= {35, b_8, &a_1};	/* struct-headers */
static cob_field f_16	= {80, b_16, &a_2};	/* var-line */
static cob_field f_17	= {37, b_17, &a_1};	/* struct-row */
static cob_field f_20	= {10, b_17 + 3, &a_4};	/* var-number */

/* End of fields */

