/* Generated by           cobc 3.1.2.0 */
/* Generated from         hellocobol.cob */
/* Generated at           Aug 04 2025 19:08:23 */
/* GnuCOBOL build date    Jul 15 2023 12:00:00 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -x -g -o hellocobol hellocobol.cob */

/* Program local variables for 'hello' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */

/* End of local data storage */

