#!/usr/bin/dh-exec
# dh-exec is needed for renaming
src/resources/seergdb_32x32.png => usr/share/icons/hicolor/32x32/apps/seergdb.png
src/resources/seergdb_64x64.png => usr/share/icons/hicolor/64x64/apps/seergdb.png
src/resources/seergdb_128x128.png => usr/share/icons/hicolor/128x128/apps/seergdb.png
src/resources/seergdb_256x256.png => usr/share/icons/hicolor/256x256/apps/seergdb.png
src/resources/seergdb_512x512.png => usr/share/icons/hicolor/512x512/apps/seergdb.png

src/resources/seergdb.desktop usr/share/applications
