cp ~/.local/share/icons/Relax-Light-Icons/actions/22/document-new.svg .
cp ~/.local/share/icons/Relax-Light-Icons/actions/22/document-open.svg .
cp ~/.local/share/icons/Relax-Light-Icons/actions/22/document-print.svg .
cp ~/.local/share/icons/Relax-Light-Icons/actions/22/document-save-as.svg .
cp ~/.local/share/icons/Relax-Light-Icons/actions/22/document-save.svg .
cp ~/.local/share/icons/Relax-Light-Icons/actions/22/edit-clear.svg .
cp ~/.local/share/icons/Relax-Light-Icons/actions/22/edit-delete.svg .
cp ~/.local/share/icons/Relax-Light-Icons/actions/22/edit-find.svg .
cp ~/.local/share/icons/Relax-Light-Icons/actions/22/go-down.svg .
cp ~/.local/share/icons/Relax-Light-Icons/actions/22/go-up.svg .
cp ~/.local/share/icons/Relax-Light-Icons/actions/22/list-add.svg .
cp ~/.local/share/icons/Relax-Light-Icons/actions/22/list-remove.svg .
cp ~/.local/share/icons/Relax-Light-Icons/actions/22/view-refresh.svg .
